name: verificación

on: 
  workflow_dispatch:

defaults:
  run:
    working-directory: ./src/verificacion

jobs:
  verificar:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm install
      - run: npm run test
